  var img=document.getElementById("imgCaptcha");
  var canvas = document.createElement("canvas");
  canvas.width = img.width;
  canvas.height = img.height;
  var ctx = canvas.getContext("2d");
  ctx.drawImage(img, 0, 0);
  var dataURL = canvas.toDataURL("image/png");
  return dataURL.replace(/^data:image\/(png|jpg);base64,/, "");
  //document.getElementsByClassName("descripcion")[0].appendChild(canvas);
  //canvas.setAttribute('id','canv');